eureka:
  instance:
    hostname: ${vcap.application.uris[0]}
    non-secure-port: 80
    leaseRenewalIntervalInSeconds: 10
  client:
    serviceUrl:
      defaultZone: https://eureka-service-v0.cfapps.io/eureka
